### PR TITLE
Memory examples

### PR DESCRIPTION
**Pull request by kquick**
Adds builds of the example programs to the cabal file to ensure that the examples remain up-to-date.
Also fixes the memory example for the additional argument to `mapRegionPointers`.

### CODE REVIEW

**Comment by travitch** [comment]
I mostly only added the examples to get syntax highlighting while I wrote the examples in Data.Macaw.Symbolic.  I'm not opposed to this change (obviously), but if we do it, we might want to just combine them into one file to save some linking time.

Alternatively, we could just get rid of them and I can turn the versions in the haddocks into doctests.  This set will be smaller, since each only has one or two declarations.

**Comment by joehendrix** [comment]
I think it'd be worth having examples to help people understand how to use macaw-symbolic, but could we add comments about what each example does?  The doctest route seems good to me to.

**Comment by joehendrix** [comment]
Is this PR still relevant?

**Comment by kquick** [comment]
Thanks for the reminder: I'll look at implementing doctests with explanations to resolve this PR.

**Comment by travitch** [comment]
Just a note: doctest is currently broken with the latest cabal versions for really dumb reasons.  I'm not sure if we want to rely on it, as it is fragile (despite me being the one who was originally agitating for doctest)

**Comment by kquick** [comment]
The doctest route is now implemented along with the associated changes in PR #107

**Pull request closed without merging**
